require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CloudbitsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Cloudbit. As you add validations to Cloudbit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CloudbitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all cloudbits as @cloudbits" do
      cloudbit = Cloudbit.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cloudbits)).to eq([cloudbit])
    end
  end

  describe "GET #show" do
    it "assigns the requested cloudbit as @cloudbit" do
      cloudbit = Cloudbit.create! valid_attributes
      get :show, {:id => cloudbit.to_param}, valid_session
      expect(assigns(:cloudbit)).to eq(cloudbit)
    end
  end

  describe "GET #new" do
    it "assigns a new cloudbit as @cloudbit" do
      get :new, {}, valid_session
      expect(assigns(:cloudbit)).to be_a_new(Cloudbit)
    end
  end

  describe "GET #edit" do
    it "assigns the requested cloudbit as @cloudbit" do
      cloudbit = Cloudbit.create! valid_attributes
      get :edit, {:id => cloudbit.to_param}, valid_session
      expect(assigns(:cloudbit)).to eq(cloudbit)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Cloudbit" do
        expect {
          post :create, {:cloudbit => valid_attributes}, valid_session
        }.to change(Cloudbit, :count).by(1)
      end

      it "assigns a newly created cloudbit as @cloudbit" do
        post :create, {:cloudbit => valid_attributes}, valid_session
        expect(assigns(:cloudbit)).to be_a(Cloudbit)
        expect(assigns(:cloudbit)).to be_persisted
      end

      it "redirects to the created cloudbit" do
        post :create, {:cloudbit => valid_attributes}, valid_session
        expect(response).to redirect_to(Cloudbit.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved cloudbit as @cloudbit" do
        post :create, {:cloudbit => invalid_attributes}, valid_session
        expect(assigns(:cloudbit)).to be_a_new(Cloudbit)
      end

      it "re-renders the 'new' template" do
        post :create, {:cloudbit => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cloudbit" do
        cloudbit = Cloudbit.create! valid_attributes
        put :update, {:id => cloudbit.to_param, :cloudbit => new_attributes}, valid_session
        cloudbit.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cloudbit as @cloudbit" do
        cloudbit = Cloudbit.create! valid_attributes
        put :update, {:id => cloudbit.to_param, :cloudbit => valid_attributes}, valid_session
        expect(assigns(:cloudbit)).to eq(cloudbit)
      end

      it "redirects to the cloudbit" do
        cloudbit = Cloudbit.create! valid_attributes
        put :update, {:id => cloudbit.to_param, :cloudbit => valid_attributes}, valid_session
        expect(response).to redirect_to(cloudbit)
      end
    end

    context "with invalid params" do
      it "assigns the cloudbit as @cloudbit" do
        cloudbit = Cloudbit.create! valid_attributes
        put :update, {:id => cloudbit.to_param, :cloudbit => invalid_attributes}, valid_session
        expect(assigns(:cloudbit)).to eq(cloudbit)
      end

      it "re-renders the 'edit' template" do
        cloudbit = Cloudbit.create! valid_attributes
        put :update, {:id => cloudbit.to_param, :cloudbit => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested cloudbit" do
      cloudbit = Cloudbit.create! valid_attributes
      expect {
        delete :destroy, {:id => cloudbit.to_param}, valid_session
      }.to change(Cloudbit, :count).by(-1)
    end

    it "redirects to the cloudbits list" do
      cloudbit = Cloudbit.create! valid_attributes
      delete :destroy, {:id => cloudbit.to_param}, valid_session
      expect(response).to redirect_to(cloudbits_url)
    end
  end

end
